import type { Dtc } from "./dtc-data";

/** Kia / Hyundai and Nissan (incl. Indian Sunny N17) specific codes. */
export const BRAND_DTCS: Dtc[] = [
  {
    code: "P0011",
    system: "engine",
    severity: "medium",
    title: { ar: "توقيت كامة الشفط متقدم أكثر من اللازم (CVVT)", en: "Camshaft position - timing over-advanced (Bank 1)" },
    meaning: {
      ar: "نظام توقيت الصمامات المتغير CVVT لا يصل للموضع المطلوب — شائع جداً في كيا وهيونداي بمحركات Gamma وNu.",
      en: "The variable valve timing (CVVT) system cannot reach the commanded position — very common on Kia/Hyundai Gamma and Nu engines.",
    },
    symptoms: {
      ar: ["صوت طقطقة عند البارد", "ضعف تسارع", "استهلاك وقود أعلى", "لمبة فحص"],
      en: ["Rattle on cold start", "Weak acceleration", "Higher fuel use", "Check-engine light"],
    },
    causes: {
      ar: ["زيت متسخ أو مستوى منخفض", "صمام OCV مسدود", "مصفاة صمام CVVT مسدودة", "جيل الكامة CVVT تالف", "تمدد جنزير التوقيت"],
      en: ["Dirty or low oil", "Clogged OCV solenoid", "Blocked CVVT filter screen", "Failed CVVT cam phaser", "Stretched timing chain"],
    },
    fixes: {
      ar: ["غيّر الزيت والفلتر بالمواصفة الصحيحة", "نظّف أو استبدل صمام OCV", "نظّف مصفاة CVVT", "افحص علامات التوقيت وشدّ الجنزير", "استبدل الـ phaser عند اللزوم"],
      en: ["Change oil and filter with the correct spec", "Clean or replace the OCV solenoid", "Clean the CVVT filter screen", "Check timing marks and chain tension", "Replace the phaser if needed"],
    },
    models: ["Kia Rio", "Kia Cerato", "Kia Sportage", "Hyundai Elantra", "Hyundai Accent"],
  },
  {
    code: "P0016",
    system: "engine",
    severity: "high",
    title: { ar: "عدم تطابق حساس الكرنك مع الكامة", en: "Crankshaft / camshaft position correlation" },
    meaning: {
      ar: "إشارتا الكرنك والكامة غير متزامنتين — غالباً تمدد جنزير التوقيت، وهو عطل معروف في كيا سيراتو ونيسان صني.",
      en: "Crank and cam signals are out of sync — usually a stretched timing chain, a known issue on Kia Cerato and Nissan Sunny.",
    },
    symptoms: { ar: ["صعوبة تشغيل", "طقطقة من غطاء التوقيت", "فقد قدرة", "انطفاء مفاجئ"], en: ["Hard starting", "Rattle from the timing cover", "Power loss", "Sudden stalling"] },
    causes: { ar: ["جنزير توقيت ممدد", "شداد جنزير ضعيف", "حساس كرنك أو كامة تالف", "صمام CVVT عالق"], en: ["Stretched timing chain", "Weak chain tensioner", "Faulty crank or cam sensor", "Stuck CVVT solenoid"] },
    fixes: { ar: ["افحص تمدد الجنزير بمقياس زاوية الكامة", "استبدل طقم التوقيت كاملاً (جنزير + شداد + دليل)", "افحص إشارة الحساسات بالراسم", "غيّر الزيت بانتظام كل 5–7 آلاف كم"], en: ["Measure chain stretch via cam timing offset", "Replace the full timing kit (chain, tensioner, guides)", "Scope the sensor signals", "Keep oil changes at 5–7k km"] },
    models: ["Kia Cerato", "Kia Rio", "Nissan Sunny N17", "Nissan Micra", "Hyundai i20"],
  },
  {
    code: "P0335",
    system: "engine",
    severity: "high",
    title: { ar: "دائرة حساس موضع الكرنك", en: "Crankshaft position sensor circuit" },
    meaning: { ar: "الكمبيوتر لا يستقبل إشارة سليمة من حساس الكرنك، فيمنع الشرارة والوقود.", en: "The ECM is not receiving a valid crank signal, so spark and fuel are cut." },
    symptoms: { ar: ["المحرك يدور ولا يشتغل", "انطفاء أثناء السير", "عداد الدوران لا يعمل"], en: ["Cranks but will not start", "Stalling while driving", "Tachometer dead"] },
    causes: { ar: ["حساس كرنك تالف (شائع في صني الهندي)", "أسلاك مقطوعة أو موصل مؤكسد", "ترس الإشارة تالف", "تشويش من كويل"], en: ["Failed crank sensor (common on Indian Sunny)", "Broken wiring or corroded connector", "Damaged reluctor ring", "Ignition noise interference"] },
    fixes: { ar: ["قِس مقاومة الحساس مقارنة بالمواصفة", "افحص الأسلاك والأرضي", "استبدل الحساس بقطعة أصلية", "افحص ترس الإشارة عند الحدافة"], en: ["Measure sensor resistance against spec", "Inspect wiring and grounds", "Replace with an OEM sensor", "Inspect the reluctor ring at the flywheel"] },
    models: ["Nissan Sunny N17", "Nissan Micra", "Kia Picanto", "Kia Rio"],
  },
  {
    code: "P0420",
    system: "emissions",
    severity: "medium",
    title: { ar: "كفاءة الحفّاز أقل من الحد", en: "Catalyst system efficiency below threshold" },
    meaning: { ar: "الحفّاز (الكاتلست) لم يعد ينظف العادم بكفاءة، أو حساس الأكسجين الخلفي يعطي قراءة خاطئة.", en: "The catalytic converter is no longer cleaning exhaust efficiently, or the rear O2 sensor is reporting wrongly." },
    symptoms: { ar: ["لمبة فحص", "رائحة عادم كريهة", "رسوب في الفحص الدوري"], en: ["Check-engine light", "Sulphur smell", "Emissions test failure"] },
    causes: { ar: ["حفّاز متقادم أو مسدود", "حساس أكسجين خلفي بطيء", "تسريب عادم قبل الحفّاز", "احتراق ناقص طويل الأمد"], en: ["Aged or clogged catalyst", "Slow downstream O2 sensor", "Exhaust leak before the catalyst", "Long-running misfire"] },
    fixes: { ar: ["أصلح أي احتراق ناقص أولاً", "افحص تسريب العادم", "قارن موجة الحساس الأمامي والخلفي", "استبدل الحفّاز إن ثبت تلفه"], en: ["Fix any misfire first", "Check for exhaust leaks", "Compare upstream vs downstream O2 waveforms", "Replace the catalyst if proven bad"] },
    models: ["Kia Rio", "Kia Sportage", "Nissan Sunny", "Nissan Sentra"],
  },
  {
    code: "P0101",
    system: "fuel",
    severity: "medium",
    title: { ar: "أداء دائرة حساس تدفق الهواء MAF", en: "MAF sensor circuit range / performance" },
    meaning: { ar: "قراءة حساس الهواء لا تتوافق مع حمل المحرك.", en: "The MAF reading does not correlate with engine load." },
    symptoms: { ar: ["تردد المحرك", "ضعف عزم", "انطفاء عند التباطؤ"], en: ["Hesitation", "Low torque", "Stalling at idle"] },
    causes: { ar: ["حساس MAF متسخ", "فلتر هواء مسدود أو رديء", "تسريب هواء بعد الحساس", "خرطوم شفط مشقوق"], en: ["Dirty MAF element", "Clogged or poor-quality air filter", "Air leak after the sensor", "Cracked intake hose"] },
    fixes: { ar: ["نظّف الحساس بمنظف MAF فقط", "استبدل فلتر الهواء", "افحص خراطيم الشفط", "قارن قراءة g/s مع المواصفة عند التباطؤ"], en: ["Clean with dedicated MAF cleaner only", "Replace the air filter", "Inspect intake hoses", "Compare g/s at idle to spec"] },
    models: ["Nissan Sunny N17", "Nissan Tiida", "Kia Cerato", "Kia Sportage"],
  },
  {
    code: "P0507",
    system: "engine",
    severity: "low",
    title: { ar: "دوران التباطؤ أعلى من المتوقع", en: "Idle air control system RPM higher than expected" },
    meaning: { ar: "الدوران عند التباطؤ أعلى مما يطلبه الكمبيوتر.", en: "Idle speed is higher than the ECM commands." },
    symptoms: { ar: ["دوران مرتفع عند التباطؤ", "السيارة تزحف عند الفرامل"], en: ["High idle", "Car creeps at stops"] },
    causes: { ar: ["خانق كهربائي متسخ", "تسريب هواء", "حاجة لإعادة تعلم التباطؤ (نيسان)", "صمام PCV تالف"], en: ["Dirty electronic throttle", "Vacuum leak", "Idle relearn required (Nissan)", "Failed PCV valve"] },
    fixes: { ar: ["نظّف جسم الخانق ثم نفّذ إعادة تعلّم التباطؤ", "افحص تسريبات الهواء", "استبدل PCV"], en: ["Clean the throttle body then run the idle relearn", "Check for vacuum leaks", "Replace the PCV valve"] },
    models: ["Nissan Sunny N17", "Nissan Micra", "Kia Rio", "Kia Picanto"],
  },
  {
    code: "P0745",
    system: "transmission",
    severity: "high",
    title: { ar: "عطل في ملف ضغط ناقل الحركة (CVT)", en: "Pressure control solenoid malfunction (CVT)" },
    meaning: { ar: "ضغط زيت ناقل الحركة غير مضبوط — مهم جداً في CVT نيسان صني.", en: "Transmission line pressure is not controlled — critical on the Nissan Sunny CVT." },
    symptoms: { ar: ["انزلاق عند التسارع", "اهتزاز", "دخول وضع الطوارئ"], en: ["Slipping on acceleration", "Judder", "Limp mode"] },
    causes: { ar: ["زيت CVT متدهور أو منخفض", "ملف ضغط تالف", "حرارة ناقل مرتفعة", "بودي فالف متسخ"], en: ["Degraded or low CVT fluid", "Failed pressure solenoid", "High transmission temperature", "Dirty valve body"] },
    fixes: { ar: ["استخدم زيت NS-3 الأصلي فقط وغيّره كل 40 ألف كم", "افحص حرارة الناقل بالبيانات الحية", "افحص/استبدل ملف الضغط", "أضف ردياتير تبريد إضافي في الأجواء الحارة"], en: ["Use genuine NS-3 fluid and change every 40k km", "Watch transmission temperature in live data", "Test/replace the pressure solenoid", "Add an auxiliary cooler in hot climates"] },
    models: ["Nissan Sunny N17", "Nissan Tiida", "Nissan Micra CVT"],
  },
  {
    code: "P1326",
    system: "engine",
    severity: "high",
    title: { ar: "حساس اهتزاز المحرك KSDS (هيونداي/كيا)", en: "Knock sensor detection system (KSDS)" },
    meaning: { ar: "نظام KSDS رصد اهتزازاً غير طبيعي يشير لتآكل محامل عمود المرفق — عطل معروف في محركات Theta II.", en: "KSDS detected abnormal vibration indicating connecting-rod bearing wear — a known Theta II engine issue." },
    symptoms: { ar: ["طقطقة معدنية", "لمبة فحص", "دخول وضع محدود"], en: ["Metallic knocking", "Check-engine light", "Limited power mode"] },
    causes: { ar: ["تآكل محامل عمود المرفق", "زيت منخفض أو متأخر التغيير", "انسداد مجاري الزيت"], en: ["Worn crankshaft bearings", "Low or overdue oil", "Blocked oil passages"] },
    fixes: { ar: ["أوقف القيادة فوراً وافحص المحرك", "افحص ضغط الزيت", "راجع حملات الضمان الخاصة بمحرك Theta II", "قد يلزم استبدال المحرك"], en: ["Stop driving and inspect the engine", "Check oil pressure", "Check Theta II engine warranty campaigns", "Engine replacement may be required"] },
    models: ["Kia Optima", "Kia Sorento", "Kia Sportage", "Hyundai Sonata"],
  },
  {
    code: "P1273",
    system: "fuel",
    severity: "medium",
    title: { ar: "حساس نسبة الهواء/الوقود A/F — قراءة فقيرة", en: "A/F sensor 1 lean shift" },
    meaning: { ar: "حساس نسبة الهواء للوقود في نيسان يقرأ خليطاً فقيراً باستمرار.", en: "The Nissan A/F ratio sensor keeps reporting a lean mixture." },
    symptoms: { ar: ["تردد", "ضعف قوة", "استهلاك وقود متغير"], en: ["Hesitation", "Power loss", "Erratic fuel economy"] },
    causes: { ar: ["تسريب هواء", "بخاخات مسدودة", "ضغط وقود منخفض", "حساس A/F متقادم"], en: ["Air leak", "Clogged injectors", "Low fuel pressure", "Aged A/F sensor"] },
    fixes: { ar: ["افحص تسريبات الشفط", "نظّف البخاخات", "قِس ضغط الوقود", "استبدل حساس A/F الأصلي"], en: ["Smoke-test the intake", "Clean the injectors", "Measure fuel pressure", "Replace with an OEM A/F sensor"] },
    models: ["Nissan Sunny", "Nissan Sentra", "Nissan X-Trail"],
  },
  {
    code: "P0138",
    system: "emissions",
    severity: "low",
    title: { ar: "جهد حساس الأكسجين الخلفي مرتفع", en: "O2 sensor circuit high voltage (Bank 1 Sensor 2)" },
    meaning: { ar: "الحساس الخلفي يعطي جهداً مرتفعاً باستمرار.", en: "The downstream sensor reports persistently high voltage." },
    symptoms: { ar: ["لمبة فحص", "استهلاك وقود أعلى قليلاً"], en: ["Check-engine light", "Slightly higher fuel use"] },
    causes: { ar: ["حساس تالف", "قِصر في الأسلاك", "خليط غني", "تلوث بالزيت أو مانع تسريب"], en: ["Failed sensor", "Short in wiring", "Rich mixture", "Contamination by oil or sealant"] },
    fixes: { ar: ["افحص الأسلاك بحثاً عن قِصر", "راقب موجة الحساس", "استبدل الحساس"], en: ["Check wiring for shorts", "Watch the sensor waveform", "Replace the sensor"] },
    models: ["Kia Rio", "Nissan Sunny", "Kia Cerato"],
  },
];
