/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ScanRouteImport } from './routes/scan'
import { Route as LiveRouteImport } from './routes/live'
import { Route as GarageRouteImport } from './routes/garage'
import { Route as ControlsRouteImport } from './routes/controls'
import { Route as CodesRouteImport } from './routes/codes'
import { Route as AssistantRouteImport } from './routes/assistant'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CodesIndexRouteImport } from './routes/codes.index'
import { Route as CodesCodeRouteImport } from './routes/codes.$code'
import { Route as ApiChatRouteImport } from './routes/api/chat'

const ScanRoute = ScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveRoute = LiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => rootRouteImport,
} as any)
const GarageRoute = GarageRouteImport.update({
  id: '/garage',
  path: '/garage',
  getParentRoute: () => rootRouteImport,
} as any)
const ControlsRoute = ControlsRouteImport.update({
  id: '/controls',
  path: '/controls',
  getParentRoute: () => rootRouteImport,
} as any)
const CodesRoute = CodesRouteImport.update({
  id: '/codes',
  path: '/codes',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantRoute = AssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CodesIndexRoute = CodesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CodesRoute,
} as any)
const CodesCodeRoute = CodesCodeRouteImport.update({
  id: '/$code',
  path: '/$code',
  getParentRoute: () => CodesRoute,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/codes': typeof CodesRouteWithChildren
  '/controls': typeof ControlsRoute
  '/garage': typeof GarageRoute
  '/live': typeof LiveRoute
  '/scan': typeof ScanRoute
  '/api/chat': typeof ApiChatRoute
  '/codes/$code': typeof CodesCodeRoute
  '/codes/': typeof CodesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/controls': typeof ControlsRoute
  '/garage': typeof GarageRoute
  '/live': typeof LiveRoute
  '/scan': typeof ScanRoute
  '/api/chat': typeof ApiChatRoute
  '/codes/$code': typeof CodesCodeRoute
  '/codes': typeof CodesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/codes': typeof CodesRouteWithChildren
  '/controls': typeof ControlsRoute
  '/garage': typeof GarageRoute
  '/live': typeof LiveRoute
  '/scan': typeof ScanRoute
  '/api/chat': typeof ApiChatRoute
  '/codes/$code': typeof CodesCodeRoute
  '/codes/': typeof CodesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assistant'
    | '/codes'
    | '/controls'
    | '/garage'
    | '/live'
    | '/scan'
    | '/api/chat'
    | '/codes/$code'
    | '/codes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assistant'
    | '/controls'
    | '/garage'
    | '/live'
    | '/scan'
    | '/api/chat'
    | '/codes/$code'
    | '/codes'
  id:
    | '__root__'
    | '/'
    | '/assistant'
    | '/codes'
    | '/controls'
    | '/garage'
    | '/live'
    | '/scan'
    | '/api/chat'
    | '/codes/$code'
    | '/codes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssistantRoute: typeof AssistantRoute
  CodesRoute: typeof CodesRouteWithChildren
  ControlsRoute: typeof ControlsRoute
  GarageRoute: typeof GarageRoute
  LiveRoute: typeof LiveRoute
  ScanRoute: typeof ScanRoute
  ApiChatRoute: typeof ApiChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/scan': {
      id: '/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof ScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live': {
      id: '/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof LiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/garage': {
      id: '/garage'
      path: '/garage'
      fullPath: '/garage'
      preLoaderRoute: typeof GarageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/controls': {
      id: '/controls'
      path: '/controls'
      fullPath: '/controls'
      preLoaderRoute: typeof ControlsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/codes': {
      id: '/codes'
      path: '/codes'
      fullPath: '/codes'
      preLoaderRoute: typeof CodesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant': {
      id: '/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/codes/': {
      id: '/codes/'
      path: '/'
      fullPath: '/codes/'
      preLoaderRoute: typeof CodesIndexRouteImport
      parentRoute: typeof CodesRoute
    }
    '/codes/$code': {
      id: '/codes/$code'
      path: '/$code'
      fullPath: '/codes/$code'
      preLoaderRoute: typeof CodesCodeRouteImport
      parentRoute: typeof CodesRoute
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CodesRouteChildren {
  CodesCodeRoute: typeof CodesCodeRoute
  CodesIndexRoute: typeof CodesIndexRoute
}

const CodesRouteChildren: CodesRouteChildren = {
  CodesCodeRoute: CodesCodeRoute,
  CodesIndexRoute: CodesIndexRoute,
}

const CodesRouteWithChildren = CodesRoute._addFileChildren(CodesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssistantRoute: AssistantRoute,
  CodesRoute: CodesRouteWithChildren,
  ControlsRoute: ControlsRoute,
  GarageRoute: GarageRoute,
  LiveRoute: LiveRoute,
  ScanRoute: ScanRoute,
  ApiChatRoute: ApiChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
